using System;
using System.Collections;
using Firebase.Auth;
using System.Collections.Generic;
using Firebase;
using Firebase.Database;
using Firebase.Extensions;
using SaveData;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.Serialization;

[Serializable]
public class PlayerData
{
    public string Username;
    public int Highschore;
    public int Coins;
    public List<string> items = new List<string> { "sword", "potion", "shield" };
    public int Level;
}

public class FirebaseDataManager : MonoBehaviour
{
    public static FirebaseDataManager Instance;

    public event Action OnRequestOfflineAccountCreation;
    public event Action OnRequestEnterGame;
    
    public PlayerData PlayerData => _playerData;
    public string UserID => _userID;

    private DatabaseReference dbRef;
    private PlayerData _playerData;
    private string _userID; //It's used to access user's database on FireBase to retrieve and send data

    private void Awake()
    {
        if (Instance == null)
            Instance = this;
        else
            DestroyImmediate(gameObject);

        DontDestroyOnLoad(gameObject);
    }

    IEnumerator Start()
    {
        _playerData = new PlayerData();

        yield return new WaitUntil(() => FireBaseInitializer.FirebaseReady);
        yield return new WaitUntil(() => FirebaseAuthManager.LoggedIn);

        dbRef = FireBaseInitializer.FirebaseDatabase.GetReference("Players");

        FirebaseAuth auth = FirebaseAuth.DefaultInstance;

        
#if UNITY_EDITOR
        _userID = $"{FireBaseInitializer.UserID}_EDITOR"; //This ID is set manually in FireBaseInitializer while playing on Unity
#else  
        _userID = auth.CurrentUser.UserId;//This ID is generated by Firebase and will be unique as long as the user stay using the same device and don't delete the app or cache 
#endif

        print("FirebaseDatabaseReference found successfully.");

        LoadPlayerData();
    }

    [ContextMenu("NextScene")]
    public void NextScene()
    {
        SceneManager.LoadScene(sceneBuildIndex: 2);
    }

    [ContextMenu("Save")]
    public void SavePlayerData(Action onSuccessfulComplete = null, Action onFailComplete = null)
    {
        string json = JsonUtility.ToJson(_playerData);
        
        dbRef.Child(_userID).SetRawJsonValueAsync(json).ContinueWithOnMainThread(task =>
        {
            if (task.IsCompletedSuccessfully)
            {
                Debug.Log("Data saved successfully.");
                onSuccessfulComplete?.Invoke(); // true = sucesso
            }
            else
            {
                string errorMsg = task.Exception?.Flatten().Message ?? "Erro desconhecido ao salvar.";
                Debug.LogError("Error saving data.: " + errorMsg);
                onFailComplete?.Invoke(); // false = falhou
            }
        });
    }

    [ContextMenu("Load")]
    public void LoadPlayerData()
    {
        print("Trying to locate player data.");

        dbRef.Child(_userID).GetValueAsync().ContinueWithOnMainThread(task =>
        {
            print($"Searching for player {_userID} data...");
            if (task.IsFaulted)
            {
                Debug.LogError("Error accessing the database: " + task.Exception);
                return;
            }

            if (task.IsCanceled)
            {
                Debug.LogWarning("Reading canceled.");
                return;
            }

            if (task.IsCompleted)
            {
                DataSnapshot snapshot = task.Result;
                if (snapshot.Exists)
                {
                    print($"User: {_userID} data found.");
                    string json = snapshot.GetRawJsonValue();
                    if (!string.IsNullOrEmpty(json))
                    {
                        PlayerData data = JsonUtility.FromJson<PlayerData>(json);
                        _playerData = data;
                        print($"Data loaded successfully.");
                        OnRequestEnterGame?.Invoke();
                    }
                }
                else
                {
                    Debug.Log($"No data found for this id: {_userID}, you need to create an offline account");
                    OnRequestOfflineAccountCreation?.Invoke();
                }
            }
        });
    }

    public void GetLeaderboard()
    {
        dbRef.OrderByChild("Score").LimitToLast(10).GetValueAsync().ContinueWithOnMainThread(task =>
        {
            if (task.IsFaulted)
            {
                Debug.LogError("Erro ao carregar leaderboard: " + task.Exception);
            }
            else if (task.IsCompleted)
            {
                DataSnapshot snapshot = task.Result;

                List<PlayerData> leaderboard = new List<PlayerData>();

                foreach (DataSnapshot child in snapshot.Children)
                {
                    string json = child.GetRawJsonValue();
                    PlayerData player = JsonUtility.FromJson<PlayerData>(json);
                    leaderboard.Add(player);
                }

                // Reverter para ordem decrescente (Firebase retorna do menor pro maior)
                leaderboard.Reverse();

                foreach (var p in leaderboard)
                {
                    Debug.Log($"{p.Username}: {p.Highschore}");
                }
            }
        });
    }
}